package logic;

public enum ExecutionCode {
	LOADSEMESTERS(2), 
	LOADCATEGORIES(3), 
	LOADCLASSESINTERNET(5),
	LOADCLASSESFILE(7),
	SEMESTERCHANGED(11),
	SETDEFAULTSEMESTER(13),
	HELPBUTTONPRESSED(17),
	ADDCOURSEPRESSED(19),
	REMOVECOURSEPRESSED(23),
	CREATESCHEDULEPRESSED(29),
	SCHEDULECREATIONSTART(31),
	SCHEDULECREATIONEND(37),
	BACKBUTTONPRESSED(41),
	GETCRNS(43),
	NOVALIDSCHEDULES(47),
	GETCOURSEINFORMATION(53),
	DRAGANDDROPCOURSE(59),
	BROWSEROPEN(61),
	BROWSERCLOSED(67),
	POPUPOPEN(71),
	POPUPCLOSED(73);

	private final long value;

	private ExecutionCode(long value) {
		this.value = value;
	}

	public long getValue() {
		return value;
	}
}
